// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfr8uXNMt4iI9QK2hD8sK7ngMpXgiFdYM',
    appId: '1:845900841870:web:af425edb5251b5e6b4dadf',
    messagingSenderId: '845900841870',
    projectId: 'expert-ai-43d53',
    authDomain: 'expert-ai-43d53.firebaseapp.com',
    storageBucket: 'expert-ai-43d53.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZUqyQKIz1cFQnWXRae2ArWDLeNoAXEws',
    appId: '1:845900841870:android:74be68697d99af6bb4dadf',
    messagingSenderId: '845900841870',
    projectId: 'expert-ai-43d53',
    storageBucket: 'expert-ai-43d53.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-HmWIlmuoaXZFW6MT76gUi1axd-EOQLM',
    appId: '1:845900841870:ios:b68a7377e978d1c7b4dadf',
    messagingSenderId: '845900841870',
    projectId: 'expert-ai-43d53',
    storageBucket: 'expert-ai-43d53.firebasestorage.app',
    iosClientId: '845900841870-kvsuetr5l3g2jcn4qh06adj0bc4pfc69.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-HmWIlmuoaXZFW6MT76gUi1axd-EOQLM',
    appId: '1:845900841870:ios:b68a7377e978d1c7b4dadf',
    messagingSenderId: '845900841870',
    projectId: 'expert-ai-43d53',
    storageBucket: 'expert-ai-43d53.firebasestorage.app',
    iosClientId: '845900841870-kvsuetr5l3g2jcn4qh06adj0bc4pfc69.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfr8uXNMt4iI9QK2hD8sK7ngMpXgiFdYM',
    appId: '1:845900841870:web:af425edb5251b5e6b4dadf',
    messagingSenderId: '845900841870',
    projectId: 'expert-ai-43d53',
    authDomain: 'expert-ai-43d53.firebaseapp.com',
    storageBucket: 'expert-ai-43d53.firebasestorage.app',
  );
}
